export const FETCH_PAINTINGS = 'FETCH_PAINTINGS';
export const SELECT_ACTIVE_PAINTING = 'SELECT_ACTIVE_PAINTING';
export const DELETE_PAINTING = 'DELETE_PAINTING';
export const CHANGE_FILTER = 'CHANGE_FILTER'
export const FILTERS = {
	ALL : 'ALL',
	NATIONAL_GALLERY : 2
}
